name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            command: build
            
          - os_name: Linux-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            command: build

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Maybe install SSL packages
        run: sudo apt-get update --yes && sudo apt-get install --yes libxcb-xfixes0-dev
        if: matrix.platform.runs-on == 'ubuntu-20.04'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: twitter-url-fixer
          target: ${{ matrix.platform.target }}
